### ISSUE TITLE
Add developer instructions

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/thebe#175]
There aren't instructions for how to install thebelab locally in order to develop it etc. This might not be clear for folks that aren't familiar with nodejs packages etc. We could either add one to the docs, or add a `CONTRIBUTING.md` file to the repo

**Comment by minrk** [comment]
Not stupid at all! And I'd love for someone who knows more npm stuff than I do to propose a good solution, because right now the example files (maybe not even all of them) have the URL for local thebelab [commented out](https://github.com/minrk/thebelab/blob/61dfc25005a80b4402922193f1e07c5e771ad979/examples/index.html#L20-L21) so you load from `[relative-path-to-repo]/lib/index.js` instead of the CDN by toggling which script tag is enabled. Loading the local build looks like:

```html
<script type="text/javascript" src="../lib/index.js"></script>
```

Maybe we could do something with templating and a test server instead of what I've used (`python -m http.server`) to make it more automatic.

**Comment by choldgraf** [comment]
Gonna close this one in favor of #233 because we have some minimal docs here now (which is what this issue was about)
