### ISSUE TITLE
Compile thebelab so it can be loaded locally?

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/thebe#196]
I'm trying to think about how we can preview changes to Thebelab in pull-requests. Right now our documentation loads Thebelab from a CDN, but at least on *latest* we should be using "master" thebelab.

Is there a way for us to compile a dev build of thebelab that we can use in our documentation and in CI/CD testing to preview changes?

Maybe @joelachance has ideas for how this could be done?

**Comment by joelachance** [comment]
@choldgraf How are deployments currently done? I'm assuming there is a number of steps to run the webpack build and upload the built file to the CDN, correct?

If I understand correctly, we'd like a preview environment for whatever is on master. There might be two ways to go here to create a staging environment:

1. Make a second CDN deployment with the latest/canary build, which could then be used in a second doc deployment. I'm assuming this might be a manual process, which we probably don't want. If this isn't manual, then this might be a good option.

2. Use a tool like Netlify to deploy a set of docs. This is a third-party integration we can connect to the repository. It will watch changes pushed to master, and can then run a given set commands. For the small number of people looking at latest builds (I'm assuming this is a small number, yes?), this should be free. You need to use quite a bit of bandwidth before they start asking for money, which I doubt we'd get remotely close to. This could run the webpack build and deploy the docs or the development.html (probably the docs).

I think the second option might be better unless we have some automated process for the first. Netlify will generate a non-obvious domain name (we can give it a custom domain, or <pick-our-own-subdomain>.netlify.com as well) for us to use as well. This would be the same every build.

Lastly, in order to flag the webpack build for the docs, I think we'd probably need to make a new entry in the Makefile and pass in the thebelab link, whether that's the webpack build for Netlify or the CDN address for an actual deployment.

Thoughts? Hopefully this all makes sense...

**Comment by choldgraf** [comment]
For Netlify that should be straightforward, we could also use CircleCI to preview the documentation (that's what I've used in other projects). I am just not sure how to build a single local JS library that we can link to when building the documentation (so we aren't linking from the CDN). If you know how to do this then it should be easy to set up a "documentation preview" on any pull request

**Comment by joelachance** [comment]
I'm wondering if I went too far earlier-- I'm going to PR a script shortly that will replace the script tag in the docs with one pointing at the local build (still need to fidget with this part). We would then put another command in the Makefile to run the script and build the docs, so we can preview it locally (not done yet).

If we can do that, is running it locally desired? Maybe we skip the deployment (aka Netlify/Surge) altogether. If we do want to deploy it, we can complete this with a Surge or Netlify step which will be very simple.

What do you think?

**Comment by choldgraf** [comment]
if we have the ability to preview the docs with the latest Thebelab build, then once @minrk gives me access to CircleCI we can set up a preview for Thebelab quite easily (or use Netlify to do it). either way, being able to preview the docs locally with changes would be quite nice

**Comment by goanpeca** [comment]
Pinging @ccordoba12

**Comment by minrk** [comment]
Local urls should work fine in the docs, as long as we do an `npm install` there and then load with `<script src="../local/path/to/lib/index.js">`. The same ought to work for CI/CD.


There's a [commented-out URL](https://github.com/minrk/thebelab/blob/6ada976578f0b54c75fd1338098b9b24ad5055a7/examples/index.html#L19-L21) in the examples to load a local build:

```html
<script type="text/javascript" src="../lib/index.js"></script>
```

When testing, I run builds with:

```
npm install
```

and toggle this script url to see what I've broken.

**Comment by joelachance** [comment]
@minrk, I worked this up, but it may or may not be overkill: https://github.com/minrk/thebelab/pull/208

Basically, running `npm run builddocs:staging` should give you docs pointing to your local build. Happy to go whatever direction here.

**Comment by choldgraf** [comment]
@joelachance did a nice job of adding this to the docs! so I am closing :-)
