### ISSUE TITLE
Migrate to JupyterHub org?

### ISSUE THREAD

**Issue by minrk** [executablebooks/thebe#214]
I feel like this has been discussed before, but I'm not finding a public record of it. @choldgraf should we move thebelab over to the jupyterhub org? It's definitely grown well beyond a personal project of mine as part of ODK.

That should make admin permissions, etc. easier to deal with.

**Comment by choldgraf** [comment]
I'm +1 on this - I think it will make it easier to build some developer support around the tool, thanks for bringing up the idea!

I guess my only question is technical: do you imagine "jupyterhub" being the right home from a technology perspective, vs. something like Jupyter Lab? I think hub makes sense, just checking that you agree. If so, I propose we open up an issue in the team-compass to make sure the hub team is OK with it.

**Comment by choldgraf** [comment]
@joelachance you have done a lot of great work here lately, what do you think?

**Comment by nthiery** [comment]
For whatever it's worth since I am rather an outsider

Indeed the migration would make much sense.

> I guess my only question is technical: do you imagine "jupyterhub"
> being the right home from a technology perspective, vs. something
> like Jupyter Lab? I think hub makes sense, just checking that you
> agree. If so, I propose we open up an issue in the team-compass to
> make sure the hub team is OK with it.

My first guess would indeed have been JupyterLab: ThebeLab is one of
many applications built on it. It turns out that it can make use of
Binder / JupyterHub to provision a Jupyter server, but it can also use
a preexisting Jupyter server. That being said, the primary question is
where things will match best in terms of team of developers.

Anyway, just 2 cents; you'll know better!

**Comment by minrk** [comment]
It definitely makes more sense technologically under jupyterlab, but contributor-wise, it's mostly jupyterhub-team folks so far so that's where my head went as a default org (orgs are more about people than technology, to me). @choldgraf if you wanted to pull it under @executablebooks that also makes a lot of sense to me.

Paging @jupyterlab (and @blink1073 and @jasongrout in case that doesn't actually ping team members) for input on whether this should go under the jupyterlab org.

**Comment by SylvainCorlay** [comment]
My first thought would also be JupyterLab (as it is a frontend thing) but it is probably fine either way.

**Comment by blink1073** [comment]
I don't think we want to view the JupyterLab org as a place to put things that aren't being actively maintained by the JupyterLab team.  I'd support moving this repo to the JupyterHub org.

**Comment by joelachance** [comment]
@choldgraf I'm happy to defer to all of these comments above-- I don't have enough knowledge about JupyterHub to make a good recommendation here.

**Comment by choldgraf** [comment]
Thinking about it a bit more, I'm happy with moving it to the JupyterHub team. I agree with @blink1073 that if we moved it to jupyterlab it might create some maintainer burden for that community since there aren't any lab people directly working on this. And in a sense, I think of thebelab as "providing backend kernels" which feels jupyterhub-y in nature haha

I think that `executablebooks` would be happy to accept it as well, though would need to ask others in that github org. Maybe that would be a nice hybrid between Lab and Hub? My only concern there is that `executablebooks` is still quite new, so I'm not sure how much we'd be able to draw attention to it from outside.

One challenge with having it in Hub is that the skillset needed to work on Thebelab is quite different from the one needed to work on Hub infrastructure (e.g., I must admit I'm still confused by the `npm` developer workflow haha).

Perhaps we should do the following:

1. Open an issue in JupyterHub asking if it's OK to move this repo there. Note the differences in technical stack used by thebelab vs. jupyterhub tech to make sure the implications in maintenance are clear
2. If folks are +1, then move it there. If folks are hesitant, then move it to `executablebooks`.
3. Either way, use this as an opportunity to make a documentation improvements pass at thebelab so that it's easier for others to use it, and to join in on development (@joelachance's work the last few weeks has been a great first start)

**Comment by choldgraf** [comment]
OK I've opened up an issue to discuss this here: https://github.com/jupyterhub/team-compass/issues/313

**Comment by choldgraf** [comment]
@minrk what are you thinking on this one? I've got maybe 1-3 weeks of engagement left before I have baby time away. I am happy to do what I can to help shepherd this forward in the meantime if you'd like to make a switch in org / name all at once.

**Comment by minrk** [comment]
I think we should go ahead and move it to executablebooks based on those discussions. Want to fire it away?

**Comment by choldgraf** [comment]
Sounds good! What does "firing it away" mean? :-)

I've just made you an `admin` under `executablebooks/`. I think you have to have admin rights on both the sending and receiving organization for this to work? I think now it's just a matter of starting the transfer and then "accepting" it.

If you'd like to also take a stab at renaming the repo this week to `thebe`, I'd be happy to help with this (maybe I'd be most-helpful in the docs rather than in the core JS files?)

**Comment by minrk** [comment]
Migrated and renamed the repo to thebe (not any of the code changes yet)

**Comment by choldgraf** [comment]
wohoo! OK I'll open an issue about finishing the migration so we can track the remaining things
