### ISSUE TITLE
Can't change theme to cobalt

### ISSUE THREAD

**Issue by FasihZafar** [executablebooks/thebe#460]
### Describe the problem

I have followed the contribution guide and managed to get there up and running on local host. After which I tried switching theme value to cobalt inside the script tag:
    <script type="text/x-thebe-config">
      {
        requestKernel: true,
        binderOptions: {
          repo: "binder-examples/requirements",
        },
        codeMirrorConfig: {
          "theme": "cobalt"
        },
      }
    </script>
But nothing changes.

### Steps to reproduce

1. follow the instructions from here https://thebe.readthedocs.io/en/latest/contribute.html#set-up-a-development-environment
2. add the them key value pair in the codeMirrorConfig dictionary

**Comment by stevejpurves** [comment]
Hi @FasihZafar 

Thanks for reporting. So it looks like the codemirror theme is not being applied at all, and I don't think there is code in place to actually implement it!

In order to apply codemirror theme, it is necessary to load the appropriate `css` file which thebe is not doing for you. However, even if I manually add the `cobalt.css` to my page, and set the option it still does not work. Perhaps we need configure codemirror differently in the version we on which is `5.61.1`.

Definitely an issue though.
