### ISSUE TITLE
Widget Generated From Cookiecutter Repo Not Working

### ISSUE THREAD

**Issue by rmorshea** [executablebooks/thebe#512]
### Describe the problem

I've created a widget using the [widget template repository](https://github.com/jupyter-widgets/widget-cookiecutter) that works great in Binder but fails with Thebe:

- repo: https://github.com/idom-team/idom-jupyter
- binder: https://mybinder.org/v2/gh/idom-team/idom-jupyter/main?filepath=notebooks%2Fintroduction.ipynb

When running in Thebe I get the error:

```
manager-base.js:273 Could not instantiate widget
utils.js:119 Error: Could not create a model.
default.js:973 Exception opening new comm
default.js:127 TypeError: Cannot read properties of undefined (reading 'IdomModel')
output_renderers.js:22 TypeError: Cannot read properties of undefined (reading 'IdomModel')
    at htmlmanager.js:72
htmlmanager.js:72 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'IdomModel')
    at htmlmanager.js:72
```

Looking a little deeper, it appears that the loader responsible for finding my JS module `idom-client-jupyter` is returning undefined:

```javascript
    loadClass(className, moduleName, moduleVersion) {
        return new Promise((resolve, reject) => {
            if (moduleName === '@jupyter-widgets/base') {
                resolve(base);
            }
            else if (moduleName === '@jupyter-widgets/controls') {
                resolve(widgets);
            }
            else if (moduleName === '@jupyter-widgets/output') {
                resolve(outputWidgets);
            }
            else if (this.loader !== undefined) {
                // where moduleName="idom-client-jupyter" and moduleVersion="^0.4.0"
                resolve(this.loader(moduleName, moduleVersion));  // <-- this is resolving to undefined
            }
            else {
                reject(`Could not load module ${moduleName}@${moduleVersion}`);
            }
        }).then((module) => {
            if (module[className]) {  // <-- which causes the cannot read properties of undefined error here
                return module[className];
            }
            else {
                return Promise.reject(`Class ${className} not found in module ${moduleName}@${moduleVersion}`);
            }
        });
    }
```

From a conversation in Gitter with some Jupyter maintainers it seems like this might be a bug in Thebe:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/4041990/138939850-5443e523-d3ea-40b5-bde9-b9efc31fdc2d.png">

### Link to your repository or website

https://github.com/idom-team/idom-jupyter

### Steps to reproduce

Running the following in a code cell will cause the error above:

```python
import idom
from idom_jupyter import LayoutWidget

@idom.component
def Demo():
    return idom.html.h1("Hello world!")

LayoutWidget(Demo())
```

(I don't have a site deployed yet where you could try this since I'm trying to see if/how I could use Thebe)

### The version of Python you're using

3.9

### Your operating system

Ubuntu 20 LTS

**Comment by stevejpurves** [comment]
@rmorshea I imagine that you may have moved on now but I have just gained enough understanding of the underlying widget management to contribute. As I understand it, that line `resolve(this.loader(moduleName, moduleVersion));` is going to invoke a module loader, `requirejs` in this case which is responsible for loading the front end js code for your extension, by trying to find it on `unpkg.com`. So if you have not published your extension front end code there then it will not load.

(On jupyterlab and the nbextension this happens when you register your extension which is why it may work on binder and locally.)

With thebe, as you have control of the page that thebe is executing on, I would try and add your extension js code to the page, making that module available. Failing that, then it seems there is no mechanism currently in thebe to support custom extensions easily.

**Comment by rmorshea** [comment]
Thanks! I had an issue working with notebooks in VSCode for what is probably a similar reasons. I suspect that if I give this a go again things should "just work" now.
