### ISSUE TITLE
`Copy to Clipboard` included in code cells when activating

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/thebe#537]
### Describe the bug

Activating Thebe will copy in the "Copy to Clipboard" text from copy-button.

![image](https://user-images.githubusercontent.com/913249/153540971-5ae0f5b1-fdfe-4b9a-9c2c-fafda0922100.png)

### Reproduce the bug

.

### List your environment

.

**Comment by stevejpurves** [comment]
@rowanc1 where did you encounter that issue? I don't see it in the cells in thebe docs.
I'd like to reproduce and take a look

**Comment by stevejpurves** [comment]
ok, reproduced this but it's not clear why it is happening. Will investigate

**Comment by stevejpurves** [comment]
confirmed that this is working with the latest `sphinx-thebe`! 

@joergbrech are you building with sphinx? can you update your dependencies and see if that fixes things.

@choldgraf that probably means that https://jupyterbook.org/interactive/thebe.html?highlight=thebe has not been redeployed since the change?

**Comment by choldgraf** [comment]
Yep - I just redeployed https://jupyterbook.org/interactive/thebe.html and the `copy to clipboard` no longer shows up, so I'll close this one!

**Comment by joergbrech** [comment]
I am using thebe via jupyter-book, so this is resolved for me as well. Thanks!
