### ISSUE TITLE
Load local or online csv file

### ISSUE THREAD

**Issue by Kandaraa** [executablebooks/thebe#544]
### Describe the bug

Hello everyone

I'm trying to load a csv file and I'm facing an issue for both local file and online ones

For the local file it show **FileNotFoundError** so what is the proper way to load loacl csv file ?
here is the code

`import pandas as pd 
df = pd.read_csv(r"X:\xxxx\xxxxx\xxx.csv") 
print(df.head())`

Even with online files which I'm pretty sure that there is no error in file constriction I got this error:
**ParserError: Error tokenizing data. C error: Expected 1 fields in line 25, saw 376** 
using this code

`import pandas as pd 
df = pd.read_csv("https://github.com/wireservice/csvkit/blob/master/examples/dummy2.csv") 
print(df.head())`

with this file : https://github.com/wireservice/csvkit/blob/master/examples/dummy2.csv

So could you please help me with the rigth way to load csv data
Thanks

### Reproduce the bug

1. Following the configuration steps
2. runing this code: 
import pandas as pd
df = pd.read_csv("https://github.com/wireservice/csvkit/blob/master/examples/dummy2.csv")
print(df.head())

**Comment by stevejpurves** [comment]
Hi @Kandaraa 

I don't think this issue is related to `thebe` persay. 

In the first instance loading from a local file, that will not work unless perhaps you've made the file available on binder by adding it to the repository that you are using to start binder. IN that case i may be available but your code would only work above when you provide the correct notebook relative path.

On the second part of your question, the url that you are using is pointing to that file on github i.e. hte page generated by github to view your `csv` file. I this you should be using the url to the raw file instead which is `https://raw.githubusercontent.com/wireservice/csvkit/master/examples/dummy2.csv`.

Either way I'd like to close this issue, as this is not `thebe` related but a more general python/jupyter usage question.
