### ISSUE TITLE
issues with myst sites using thebe-lite

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/thebe#737]
### Describe the bug

**context**
When I do visit https://rowanc1.github.io/myst-lite/matplotlib

**expectation**
I expected jupyterlite examples to work for ipywidget

**bug**
But instead there are errors loading ipywidgets when in notebooks

![image](https://github.com/executablebooks/thebe/assets/1473646/a0ef0c41-bcc4-48a1-a87a-09617a730453)

```console
$ jupyter-book build mybook
ERROR ...
```

**problem**
This is a problem for deploying myst sites with ipywidgets

### Reproduce the bug

https://rowanc1.github.io/myst-lite/matplotlib

### List your environment

this is an issue with an already deployed site

**Comment by jtpio** [comment]
It looks similar to the previous issue: https://github.com/executablebooks/thebe/issues/689

Unfortunately this is likely to happen after each ipywidgets release. But for now it should be fixed in the latest version of `jupyterlite-pyodide-kernel`. So bumping the dependency to the latest should help.

**Comment by jtpio** [comment]
Opened https://github.com/executablebooks/thebe/pull/738 to bump the version
